### PR TITLE
Facter 1.6.17 update

### PR DESCRIPTION
**Pull request by aboe76**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Ugh, still got 5 weird commits in there, no idea why. You should rebase sometime :)

Still the diff is sane, so I can squash and merge that now. Thanks!

**Comment by GregSutcliffe** [comment]
Actually, I think I already released 1.6.17 - didn;t you already submit this?

**Comment by GregSutcliffe** [comment]
Yeah:

commit bd5d769bd42e09ed0ff5cbab3e910fa5f50eac2b
Author: Niels Abspoel aboe76@gmail.com
Date:   Fri Dec 28 19:39:46 2012 +0100

```
Updated facter to 1.6.17
Updated puppet to 3.0.2
Updated ruby-hiera to 1.1.2
```

**Comment by GregSutcliffe** [comment]
I think we can close this... do you agree @aboe76 ?

**Comment by aboe76** [comment]
yes I agree

**Pull request closed without merging**
