### PR TITLE
Puppet 3.1.0 final

### PR DESCRIPTION
**Pull request by aboe76**
updated to 3.1.0 final, build from gem

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Can we make it depend on facter || ruby-facter? I'm concerned about how people upgrade - there's no conflict on facter, and ruby-facter installs the same stuff, so what's the point? Does ruby-facter provide facter also?

Awesome work as ever, by the way ;)

**Comment by aboe76** [comment]
I think you're right, about facter || ruby-facter... only difference between the two is the place where stuff gets installed,
ruby-facter installs in /usr/lib/ruby/gems/
facter installs in /usr/lib/ruby/site_ruby/

both provide facter but ruby-facter is easier to maintain.

**Comment by GregSutcliffe** [comment]
i'm happy to drop the facter package and let joschi maintain ruby-facter. Should we ask him if he wants to add facter to the provides?

**Comment by aboe76** [comment]
sure than he can drop ruby-puppet. because this provides it.
so it's like a trade

2013/2/5 Greg Sutcliffe notifications@github.com

**Comment by GregSutcliffe** [comment]
Getting some conflicts when I try to build this. Looks like we're depending on a package that provies /usr/bin/hiera and also installing ourselves. Looking into it now, but if you know the answer....

**Comment by GregSutcliffe** [comment]
I think installing the hiera gem inside the $pkgdir is leaving files behind - it cleans up _some_ of them by calling "gem uninstall hiera" after you copy the files out, but that causes the PKGBUILD to ask for input. What are we taking from the hiera gem?

**Comment by GregSutcliffe** [comment]
Ok, so removing the hiera gem entirely seems to work - do we need it for anything @aboe76?

**Comment by GregSutcliffe** [comment]
Also the systemd files aren't copied into place. trying to fix that now

**Comment by GregSutcliffe** [comment]
Scratch that, they are, but fsr aren't starting right. Will get back to you on why...

**Comment by GregSutcliffe** [comment]
Ok, it's working now, must have done something stupid to my previous VM. Going to push a fixed version of this, check it out when you have a chance.

**Comment by aboe76** [comment]
It looks good, what was the reason hiera 1.0.0 not needed?
I was trying on a fresh archlinux vm and I could only get it working with
hiera 1.0.0 and hiera 1.1.2 installed???

2013/2/8 Greg Sutcliffe notifications@github.com

**Comment by GregSutcliffe** [comment]
With the hiera gem in the PKGBUILD, the file "/usr/bin/hiera" conflicts with the ruby-hiera package. Do you still have the test case for the hiera problem? I can test it against my PKGBUILD... Maybe we should add a tests folder to the repo ;)

**Comment by GregSutcliffe** [comment]
3.1 published, closing this.

**Pull request closed without merging**
